AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura con 2 instancias EC2 en alta disponibilidad detrás de un Load Balancer con NGINX

Parameters:
  KeyName:
    Description: Nombre del par de llaves SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: Key pairs
    ConstraintDescription: Debe ser un nombre válido de un KeyPair existente en tu cuenta.

Mappings:
  RegionMap:
    us-east-1:
      AZ1: us-east-1a
      AZ2: us-east-1b
      AZ3: us-east-1c
      AZ4: us-east-1d
      AZ5: us-east-1e

Resources:
  WebVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-GrupoG8

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", AZ1]
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", AZ2]
      MapPublicIpOnLaunch: true

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", AZ3]
      MapPublicIpOnLaunch: true

  PublicSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", AZ4]
      MapPublicIpOnLaunch: true

  PublicSubnet5:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WebVPC
      CidrBlock: 10.0.5.0/24
      AvailabilityZone: !FindInMap [RegionMap, !Ref "AWS::Region", AZ5]
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref WebVPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebVPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet3
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation4:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet4
      RouteTableId: !Ref RouteTable

  SubnetRouteTableAssociation5:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet5
      RouteTableId: !Ref RouteTable

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP y SSH
      VpcId: !Ref WebVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref WebSG
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (us-east-1)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl enable nginx
          echo "<h1>Grupo 8 - EC2 1</h1>" > /var/www/html/index.html
          sudo systemctl restart nginx
      Tags:
        - Key: Name
          Value: EC2-Servidor1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet2
      SecurityGroupIds:
        - !Ref WebSG
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (us-east-2)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl enable nginx
          echo "<h1>Grupo 8 - EC2 2</h1>" > /var/www/html/index.html
          sudo systemctl restart nginx
      Tags:
        - Key: Name
          Value: EC2-Servidor2

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet3
      SecurityGroupIds:
        - !Ref WebSG
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (us-west-1)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl enable nginx
          echo "<h1>Grupo 8 - EC2 3</h1>" > /var/www/html/index.html
          sudo systemctl restart nginx
      Tags:
        - Key: Name
          Value: EC2-Servidor3

  EC2Instance4:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet4
      SecurityGroupIds:
        - !Ref WebSG
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (us-west-2)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl enable nginx
          echo "<h1>Grupo 8 - EC2 4</h1>" > /var/www/html/index.html
          sudo systemctl restart nginx
      Tags:
        - Key: Name
          Value: EC2-Servidor4

  EC2Instance5:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet5
      SecurityGroupIds:
        - !Ref WebSG
      ImageId: ami-084568db4383264d4 # Ubuntu Server 24.04 LTS (us-east-1)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y
          sudo systemctl enable nginx
          echo "<h1>Grupo 8 - EC2 5</h1>" > /var/www/html/index.html
          sudo systemctl restart nginx
      Tags:
        - Key: Name
          Value: EC2-Servidor5

  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3
        - !Ref PublicSubnet4
        - !Ref PublicSubnet5
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: 2
        UnhealthyThreshold: 5
        Interval: 30
        Timeout: 5
      Instances:
        - !Ref EC2Instance1
        - !Ref EC2Instance2
        - !Ref EC2Instance3
        - !Ref EC2Instance4
        - !Ref EC2Instance5
      SecurityGroups:
        - !Ref WebSG
      CrossZone: true
      Tags:
        - Key: Name
          Value: LoadBalancer-Grupo8

Outputs:
  LoadBalancerDNSName:
    Description: "DNS del Load Balancer"
    Value: !GetAtt LoadBalancer.DNSName
